services:
  server:
    build:
      context: ./backend
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./backend/package.json:/usr/src/app/package.json
      - ./backend/nodemon.json:/usr/src/app/nodemon.json

  website:
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/index.html:/usr/src/app/index.html
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./frontend/vite.config.ts:/usr/src/app/vite.config.ts
      - ./frontend/package.json:/usr/src/app/package.json
    depends_on:
      - server 