services:
  mongodb:
    image: mongo:8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo_data:/data/db

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025 # Web UI
      - 1025:1025 # SMTP
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  server:
    build:
      context: ./backend
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongodb
      - mailpit
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://root:1234@mongodb:27017/tfg?authSource=admin
      - JWT_SECRET=secret
      - JWT_EXPIRATION=30d
      - FRONTEND_URL=http://localhost:5173
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USER=any
      - SMTP_PASS=any
      - SMTP_FROM=TFG <noreply@tfg.local>

  website:
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_BACKEND_API_BASE_URL: "http://localhost:3000"
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    depends_on:
      - server

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:
